name: Set Environment Secret
on:
  push:
    branches:
      - master

jobs:
  set-env-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Secret
        env:
          REACT_APP_API_KEY: ${{ secrets.API_KEY }}
        run: echo "REACT_APP_API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
